### ISSUE TITLE
Possible memory leak detected

### ISSUE THREAD

**Issue by heks** [mattkrick/redux-optimistic-ui#13]
I keep getting this error if I do optimistic actions too fast.

```
@@optimist: Possible memory leak detected.
                  Verify all actions result in a commit or revert and
                  don't use optimistic-UI for long-running server fetches
```

What is the reason?

**Comment by mattkrick** [comment]
That means you've put in a request, then > 100 actions have been dispatched before that action was committed.

**Comment by mattkrick** [comment]
Closing, feel free to reopen if not resolved.
