### ISSUE TITLE
Reducer not getting called after COMMIT/REVERT

### ISSUE THREAD

**Issue by mwalsher** [mattkrick/redux-optimistic-ui#5]
It seems the reducer isn't being called after an optimistic action is committed/reverted. Is this intentional? Or am I missing something? If I remove the `optimistic` value from `meta`, the reducer is called as expected.

Basically I am trying to set an error message in the event that an optimistic action fails. Looking at your meatier example, it seems that this should be possible?

Here is the relevant API code which dispatches the optimistic actions:

```
const [ requestType, successType, failureType ] = types

// Allow the requestType action to continue being dispatched
next(_actionWith(action, Object.assign({}, { type: requestType },
  optimistic ? { meta: { optimistic: { type: BEGIN, id: transactionId } } } : {}
)))

// Call the API
return _callApi(endpoint, schema, method, payload).then(
  // If successful, dispatch the successType action and COMMIT the optimistic transaction
  response => {
    let nextActionParams = _actionWith(action, Object.assign({}, { type: successType, payload: response },
      optimistic ? { meta: { optimistic: { type: COMMIT, id: transactionId } } } : {}
    ))
    return next(nextActionParams)
  },
  // If unsuccessful, dispatch the failureType action and REVERT the optimistic transaction
  error => {
    let nextActionParams = _actionWith(action, Object.assign({},
      { type: failureType, error: error.message || 'Something bad happened' },
      optimistic ? { meta: { optimistic: { type: REVERT, id: transactionId } } } : {}
    ))
    return next(nextActionParams)
  }
).catch(error => {
  debugger
})

function _actionWith (action, data) {
  const finalAction = Object.assign({}, action, data)
  delete finalAction.meta[API_CALL]
  return finalAction
}
```

**Comment by mwalsher** [comment]
It looks like `historyWithoutRevert` is empty when the revert is being applied, which I believe is why the reducer isn't being called.

**Comment by mattkrick** [comment]
So your callback adds an error message and ACTION_ERROR should put that in
the state

**Comment by mwalsher** [comment]
That's exactly what is supposed to happen (and in fact does happen if I set `optimistic: false` to disable your reducer enhancer), however my ACTION_ERROR action isn't getting triggered when a REVERT occurs.

**Comment by mwalsher** [comment]
Changing your code as follows fixes the issue:

```
case COMMIT:
  let committedState = applyRevert(state, id, reducer)
  return committedState.withMutations(mutState => {
    mutState
      .set('history', mutState.get('history').push(action))
      .set('current', reducer(mutState.get('current'), action))
      .set('beforeState', mutState.get('current'))
  })
case REVERT:
  let revertedState = applyRevert(state, id, reducer)
  return revertedState.withMutations(mutState => {
    mutState
      .set('history', mutState.get('history').push(action))
      .set('current', reducer(mutState.get('current'), action))
      .set('beforeState', mutState.get('current'))
  })
```

**Comment by mattkrick** [comment]
could you write a failing test case? I still think this is a middleware error instead of something wrong with the package

**Comment by mattkrick** [comment]
reading through this again, are you saying that you commit something and THEN revert it? If so then that's expected behavior. SUCCESS & ERROR are mutually exclusive

**Comment by mattkrick** [comment]
believe this is was an implementation problem, since the optimistic-ui result should be part of the action meta data & not an action itself
